title:                        Mineralogy Extension
acronym:                      MinExt
documentation-landing-page:   # Landing Page URL of the standard documentation
github-repo:                  # URL of the GitHub Repo
source-data-files:            # Full URL to Source Files as YAML List

source-md-files:              # Full URL of Source Markdown content files as YAML List

last-modified:                # Date file last modified
comments:                     # General remarks about the StaDocGen instance for standard